application: j-errico
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /changelog
  static_files: static/changelog.html
  upload: static/changelog.html

- url: /console/
  login: required
  static_files: static/console.html
  upload: static/console.html

- url: /static/(.*\.(gif|png|jpg|js|css|less|ico|woff|tff|svg|eot|tmpl))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|js|css|less|ico|woff|tff|svg|eot|tmpl))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
